<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Fun (base.Caml.Fun)</title><link rel="stylesheet" href="../../../_odoc-theme/odoc.css"/><meta charset="utf-8"/><meta name="generator" content="odoc v1.1.1-1373-g2e7c1c75"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><script src="../../../highlight.pack.js"></script><script>hljs.initHighlightingOnLoad();</script></head><body><nav><a href="../index.html">Up</a> â€“ <a href="../../index.html">base</a> &#x00BB; <a href="../index.html">Caml</a> &#x00BB; Fun</nav><header><h1>Module <code>Caml.Fun</code></h1></header><nav class="toc"><ul><li><a href="#combinators">Combinators</a></li><li><a href="#exception">Exception handling</a></li></ul></nav><div class="content"><aside><p>Function manipulation.</p><dl><dt>since</dt><dd>4.08</dd></dl></aside><h2 id="combinators"><a href="#combinators" class="anchor"></a>Combinators</h2><div><div class="spec external" id="val-id" class="anchored"><a href="#val-id" class="anchor"></a><code><span class="keyword">val</span> id : <span class="type-var">'a</span> <span>&#45;&gt;</span> <span class="type-var">'a</span></code></div><div><p><code>id</code> is the identity function. For any argument <code>x</code>, <code>id x</code> is <code>x</code>.</p></div></div><div><div class="spec value" id="val-const" class="anchored"><a href="#val-const" class="anchor"></a><code><span class="keyword">val</span> const : <span class="type-var">'a</span> <span>&#45;&gt;</span> <span class="type-var">_</span> <span>&#45;&gt;</span> <span class="type-var">'a</span></code></div><div><p><code>const c</code> is a function that always returns the value <code>c</code>. For any argument <code>x</code>, <code>(const c) x</code> is <code>c</code>.</p></div></div><div><div class="spec value" id="val-flip" class="anchored"><a href="#val-flip" class="anchor"></a><code><span class="keyword">val</span> flip : <span>(<span class="type-var">'a</span> <span>&#45;&gt;</span> <span class="type-var">'b</span> <span>&#45;&gt;</span> <span class="type-var">'c</span>)</span> <span>&#45;&gt;</span> <span class="type-var">'b</span> <span>&#45;&gt;</span> <span class="type-var">'a</span> <span>&#45;&gt;</span> <span class="type-var">'c</span></code></div><div><p><code>flip f</code> reverses the argument order of the binary function <code>f</code>. For any arguments <code>x</code> and <code>y</code>, <code>(flip f) x y</code> is <code>f y x</code>.</p></div></div><div><div class="spec value" id="val-negate" class="anchored"><a href="#val-negate" class="anchor"></a><code><span class="keyword">val</span> negate : <span>(<span class="type-var">'a</span> <span>&#45;&gt;</span> bool)</span> <span>&#45;&gt;</span> <span class="type-var">'a</span> <span>&#45;&gt;</span> bool</code></div><div><p><code>negate p</code> is the negation of the predicate function <code>p</code>. For any argument <code>x</code>, <code>(negate p) x</code> is <code>not (p x)</code>.</p></div></div><h2 id="exception"><a href="#exception" class="anchor"></a>Exception handling</h2><div><div class="spec value" id="val-protect" class="anchored"><a href="#val-protect" class="anchor"></a><code><span class="keyword">val</span> protect : <span>finally:<span>(unit <span>&#45;&gt;</span> unit)</span></span> <span>&#45;&gt;</span> <span>(unit <span>&#45;&gt;</span> <span class="type-var">'a</span>)</span> <span>&#45;&gt;</span> <span class="type-var">'a</span></code></div><div><p><code>protect ~finally work</code> invokes <code>work ()</code> and then <code>finally ()</code> before <code>work ()</code> returns with its value or an exception. In the latter case the exception is re-raised after <code>finally ()</code>. If <code>finally ()</code> raises an exception, then the exception <a href="index.html#exception-Finally_raised"><code>Finally_raised</code></a> is raised instead.</p><p><code>protect</code> can be used to enforce local invariants whether <code>work ()</code> returns normally or raises an exception. However, it does not protect against unexpected exceptions raised inside <code>finally ()</code> such as <a href="../../../ocaml/Stdlib/index.html#exception-Out_of_memory"><code>Stdlib.Out_of_memory</code></a>, <a href="../../../ocaml/Stdlib/index.html#exception-Stack_overflow"><code>Stdlib.Stack_overflow</code></a>, or asynchronous exceptions raised by signal handlers (e.g. <a href="../Sys/index.html#exception-Break"><code>Sys.Break</code></a>).</p><p>Note: It is a <em>programming error</em> if other kinds of exceptions are raised by <code>finally</code>, as any exception raised in <code>work ()</code> will be lost in the event of a <a href="index.html#exception-Finally_raised"><code>Finally_raised</code></a> exception. Therefore, one should make sure to handle those inside the finally.</p></div></div><div><div class="spec exception" id="exception-Finally_raised" class="anchored"><a href="#exception-Finally_raised" class="anchor"></a><code><span class="keyword">exception</span> <span class="exception">Finally_raised</span> <span class="keyword">of</span> exn</code></div><div><p><code>Finally_raised exn</code> is raised by <code>protect ~finally work</code> when <code>finally</code> raises an exception <code>exn</code>. This exception denotes either an unexpected exception or a programming error. As a general rule, one should not catch a <code>Finally_raised</code> exception except as part of a catch-all handler.</p></div></div></div></body></html>